### ISSUE TITLE
Epi2me labs not working on Mac/Ubuntu

### ISSUE THREAD

**Issue by rafiahmad-lab** [epi2me-labs/labslauncher#10]
I tried to download and use the Epi2ME lab on two different machines using Mac OSX (Big Sur) and Ubuntu 18.04 and I get the same error:

Traceback (most recent call last):
File "build/EPI2ME-Labs-Launcher/labslauncher-script.py", line 2, in <module>
File "labslauncher/app.py", line 1120, in launcher_main
File "labslauncher/app.py", line 735, in __init__
File "labslauncher/app.py", line 510, in __init__
File "labslauncher/app.py", line 538, in on_status
File "labslauncher/app.py", line 800, in show_message
RuntimeError: super-class __init__() of type LabsLauncherGUI was never called
 

Could you help me fix it.

**Comment by cjw85** [comment]
@rafiahmad-lab,

Apologies for the lack of a response here. Can you indicate if you resolved this issue? I have just tested the macOS package available from the [Downloads](https://labs.epi2me.io/downloads/) page, and it appears to work correctly for me.

**Comment by cjw85** [comment]
Closing for lack of response.
