### ISSUE TITLE
Unable update labslauncher from cli

### ISSUE THREAD

**Issue by cantaylancapraz** [epi2me-labs/labslauncher#11]
Hi,

When I run `labsmanager --update` command, I got following error. What can be the reason for that? Also, can I use --update option for specific version?

Thanks

```
[15:28:38 - Launcher] * Welcome to the EPI2MELabs launcher CLI *
[15:28:38 - Launcher] Server update available: None -> v1.0.10.
[15:28:38 - Launcher] Request to update container.
[15:28:38 - Launcher] Upgrading server: None -> v1.0.10.
[15:28:38 - Launcher] Starting thread to pull image.
[15:28:38 - DckrClnt] Starting pull of image tag: v1.0.10.
[15:28:42 - Launcher] Downloading: 0%
[15:28:55 - Launcher] Downloading: 5%
[15:29:06 - Launcher] Downloading: 10%
[15:29:17 - Launcher] Downloading: 15%
[15:29:29 - Launcher] Downloading: 20%
[15:29:39 - Launcher] Downloading: 25%
[15:29:51 - Launcher] Downloading: 70%
[15:30:03 - Launcher] Downloading: 75%
[15:30:18 - Launcher] Downloading: 80%
[15:30:37 - Launcher] Downloading: 85%
[15:30:51 - Launcher] Downloading: 90%
[15:31:04 - Launcher] Downloading: 95%
[15:31:16 - Launcher] Downloading: 100%
[15:31:16 - Runnabl] Failed to execute runnable:
fn: <bound method DockerClient.pull_image of <labslauncher.dockerutil.DockerClient object at 0x7f30bcf4eac0>>
args: ()
kwargs: {'progress': <bound PYQT_SIGNAL progress of WorkerSignals object at 0x7f30b486cf70>, 'stopped': <threading.Event object at 0x7f30b4879e80>}
Traceback (most recent call last):
  File "docker/api/client.py", line 261, in _raise_for_status
  File "requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/ontresearch/epi2melabs-notebook:v1.0.10/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher/qtext.py", line 107, in run
  File "labslauncher/dockerutil.py", line 337, in pull_image
  File "docker/models/images.py", line 316, in get
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 245, in inspect_image
  File "docker/api/client.py", line 267, in _result
  File "docker/api/client.py", line 263, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: ontresearch/epi2melabs-notebook:v1.0.10: No such image: ontresearch/epi2melabs-notebook:v1.0.10")
```

**Comment by cjw85** [comment]
Hi @cantaylancapraz,

Apologies for the lack of a response here. Im unsure why this has failed. I just ran the command myself and it completed successfully:
```
[16:13:15 - Launcher] Server update available: None -> v1.0.10.
[16:13:15 - Launcher] Request to update container.
[16:13:15 - Launcher] Upgrading server: None -> v1.0.10.
[16:13:15 - Launcher] Starting thread to pull image.
[16:13:15 - DckrClnt] Starting pull of image tag: v1.0.10.
[16:13:17 - Launcher] Downloading: 0%
...
[16:14:51 - Launcher] Downloading: 100%
[16:14:51 - DckrClnt] Finished pulling image
[16:14:51 - Launcher] Server updated, restart the server for changes to take effect.
```

Can you try again? I wonder if there was an intermittent connection errors with dockerhub.

**Comment by cjw85** [comment]
I should say, to use specific version it is probably easiest to simply use the docker CLI. For example:

```
docker pull ontresearch/epi2melabs-notebook:v1.0.8
```

will fetch version v1.0.8. You can then run:

```
labsmanager --fixed_tag v1.0.8 --start
```

To start a server using this version.

**Comment by callumparr** [comment]
I am also having this issue using labsmanager
