### ISSUE TITLE
Launcher error

### ISSUE THREAD

**Issue by sumin5784** [epi2me-labs/labslauncher#13]
Hello,

I followed tutorials on epi2melabs blog, but I'm having troubles.
On my linux machine, I have error that docker can't communicate with the epi2melab lauchers.
I also tried on my window machine, and every time I launched epi2melab laucher, 
Laucher error prompted.

On both machines,
I installed docker, checked docker was working properly, and I also pulled epi2melab images.

In tutorial webpage, said "simply download launcher", but it is not simply working.
Are there any necessary steps to make docker and launcher communicate?

Feedbacks would be appreciated! Thank you for the help in advance.

**Comment by amblina** [comment]
Hi Sumin,
Sorry to hear you are having these issues, could you please confirm the version of the launcher you are running and the version of docker you are running?  Could you also include (in full) the error messages you are receiving either as a screenshot or copied and pasted so I can look at replicating this issue.

Thanks!
Amber

**Comment by sumin5784** [comment]
Hello Amber,

Thank you so much for the response.
I just newly entered ONT data, and I came across docker and epi2melabs at this London calling 2021.
I want to set-up epi2melab environment for pipeline and downstream analysis.
Thank you for the help in advance.


I just followed instructions in Epi2melabs web page, the quick installation.
I installed docker, and installed launcher.
***@***.***D752F9.67178D10]


I checked out docker is running, and it's working properly:
***@***.***D752F9.635D1D20]


And then I opened launcher, but I got errors:
***@***.***D752F9.635D1D20]
***@***.***D752F9.635D1D20]


I tried myself to figure it out, but failed, so I installed docker on my window machine and tried again.
But, I think I have the same error.

***@***.***D752F9.67178D10]



Best regards,
Sumin Jo



From: amblina ***@***.***>
Sent: Wednesday, May 26, 2021 10:49 AM
To: epi2me-labs/labslauncher ***@***.***>
Cc: Sumin Jo ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [epi2me-labs/labslauncher] Launcher error (#13)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Hi Sumin,
Sorry to hear you are having these issues, could you please confirm the version of the launcher you are running and the version of docker you are running? Could you also include (in full) the error messages you are receiving either as a screenshot or copied and pasted so I can look at replicating this issue.

Thanks!
Amber

-

**Comment by amblina** [comment]
Hi Sumin, 
Unfortunately it looks like the attachments you added aren't loading on github - could you try attach them again to this ticket on the github website: https://github.com/epi2me-labs/labslauncher/issues/13?
Thanks!
Amber

**Comment by sumin5784** [comment]
Hi Amber,

I attached screen shots here.

![1](https://user-images.githubusercontent.com/65312235/120035472-46f6b280-bfc4-11eb-8c50-b5ce65126e6a.png)

![2](https://user-images.githubusercontent.com/65312235/120035519-5d047300-bfc4-11eb-9ba0-0812e0829010.png)

![3](https://user-images.githubusercontent.com/65312235/120035527-5f66cd00-bfc4-11eb-9269-262a904a7214.png)

![4](https://user-images.githubusercontent.com/65312235/120035529-6097fa00-bfc4-11eb-8e79-33887e84e385.png)

**Comment by st-pfister** [comment]
Hey there,
thanks for opening this conversation! I am a complete bioinformatics beginner and am trying to get EPI2ME Labs notebook server working on my Mac via the EPI2MELabs Launcher and Docker, but I cannot start a server successfully. In Docker, I am getting a server error message (HTTP code 500) that my "ports are not available" and that also the "bind: address is already in use". In EPI2MELabs, it just says that the server is created, but last attempt to start failed. I did not change any of the three. pre-set options for server/token/port yet. And suggestions what I am doing wrong?

Thanks in advance!

**Comment by amblina** [comment]
Hi @sumin5784, sorry I missed this message! Would you be able to send us the log file in C:\Users\Sumin\.labslauncher which will give us some clues as to what is happening on your machine!

**Comment by sumin5784** [comment]
Here's log file: 

[12:55:29 - labslauncher] Starting application.
[12:55:30 - labslauncher] Uncaught exception:
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 158, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 301, in connect
  File "lib\site-packages\urllib3\connection.py", line 167, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000021CB75AFFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 439, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021CB75AFFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher-script.py", line 2, in <module>
  File "labslauncher\app.py", line 1130, in launcher_main
  File "labslauncher\app.py", line 746, in __init__
  File "labslauncher\app.py", line 488, in __init__
  File "labslauncher\__init__.py", line 109, in app_releases
  File "lib\site-packages\github\MainClass.py", line 271, in get_user
  File "lib\site-packages\github\Requester.py", line 318, in requestJsonAndCheck
  File "lib\site-packages\github\Requester.py", line 410, in requestJson
  File "lib\site-packages\github\Requester.py", line 486, in __requestEncode
  File "lib\site-packages\github\Requester.py", line 513, in __requestRaw
  File "lib\site-packages\github\Requester.py", line 110, in getresponse
  File "lib\site-packages\requests\sessions.py", line 537, in get
  File "lib\site-packages\requests\sessions.py", line 524, in request
  File "lib\site-packages\requests\sessions.py", line 637, in send
  File "lib\site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021CB75AFFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

[13:06:56 - labslauncher] Starting application.
[13:06:56 - labslauncher] Uncaught exception:
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 158, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 301, in connect
  File "lib\site-packages\urllib3\connection.py", line 167, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001DD5FF9FFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 439, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DD5FF9FFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher-script.py", line 2, in <module>
  File "labslauncher\app.py", line 1130, in launcher_main
  File "labslauncher\app.py", line 746, in __init__
  File "labslauncher\app.py", line 488, in __init__
  File "labslauncher\__init__.py", line 109, in app_releases
  File "lib\site-packages\github\MainClass.py", line 271, in get_user
  File "lib\site-packages\github\Requester.py", line 318, in requestJsonAndCheck
  File "lib\site-packages\github\Requester.py", line 410, in requestJson
  File "lib\site-packages\github\Requester.py", line 486, in __requestEncode
  File "lib\site-packages\github\Requester.py", line 513, in __requestRaw
  File "lib\site-packages\github\Requester.py", line 110, in getresponse
  File "lib\site-packages\requests\sessions.py", line 537, in get
  File "lib\site-packages\requests\sessions.py", line 524, in request
  File "lib\site-packages\requests\sessions.py", line 637, in send
  File "lib\site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DD5FF9FFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

[13:10:31 - labslauncher] Starting application.
[13:10:31 - labslauncher] Uncaught exception:
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 158, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 301, in connect
  File "lib\site-packages\urllib3\connection.py", line 167, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002243E73FFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 439, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002243E73FFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher-script.py", line 2, in <module>
  File "labslauncher\app.py", line 1130, in launcher_main
  File "labslauncher\app.py", line 746, in __init__
  File "labslauncher\app.py", line 488, in __init__
  File "labslauncher\__init__.py", line 109, in app_releases
  File "lib\site-packages\github\MainClass.py", line 271, in get_user
  File "lib\site-packages\github\Requester.py", line 318, in requestJsonAndCheck
  File "lib\site-packages\github\Requester.py", line 410, in requestJson
  File "lib\site-packages\github\Requester.py", line 486, in __requestEncode
  File "lib\site-packages\github\Requester.py", line 513, in __requestRaw
  File "lib\site-packages\github\Requester.py", line 110, in getresponse
  File "lib\site-packages\requests\sessions.py", line 537, in get
  File "lib\site-packages\requests\sessions.py", line 524, in request
  File "lib\site-packages\requests\sessions.py", line 637, in send
  File "lib\site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002243E73FFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

[13:00:48 - labslauncher] Starting application.
[13:00:48 - labslauncher] Uncaught exception:
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 158, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 301, in connect
  File "lib\site-packages\urllib3\connection.py", line 167, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000216C33FFFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 439, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000216C33FFFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher-script.py", line 2, in <module>
  File "labslauncher\app.py", line 1130, in launcher_main
  File "labslauncher\app.py", line 746, in __init__
  File "labslauncher\app.py", line 488, in __init__
  File "labslauncher\__init__.py", line 109, in app_releases
  File "lib\site-packages\github\MainClass.py", line 271, in get_user
  File "lib\site-packages\github\Requester.py", line 318, in requestJsonAndCheck
  File "lib\site-packages\github\Requester.py", line 410, in requestJson
  File "lib\site-packages\github\Requester.py", line 486, in __requestEncode
  File "lib\site-packages\github\Requester.py", line 513, in __requestRaw
  File "lib\site-packages\github\Requester.py", line 110, in getresponse
  File "lib\site-packages\requests\sessions.py", line 537, in get
  File "lib\site-packages\requests\sessions.py", line 524, in request
  File "lib\site-packages\requests\sessions.py", line 637, in send
  File "lib\site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/epi2me-labs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000216C33FFFD0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

**Comment by amblina** [comment]
Hi @sumin5784,
Can I confirm which port you are trying to setup Labslauncher with - are you using the default of 8888 and 8889 or are you customizing this while running it?
Thanks!
Amber

**Comment by sumin5784** [comment]
Hi amblina,

I think it's default? cause I didn't change or set anything regarding port.

**Comment by amblina** [comment]
I suspect that this might be because python is being blocked from making outbound requests by your local setup. This can be due to firewall/antivirus or an explicit rule blocking it.  If you are able to (and you wish to experiment!) I can give you the basic steps below, however I strongly advise talking to your local administrator before doing this:

Accessing windows firewall settings:

![image](https://user-images.githubusercontent.com/999897/123327033-db0b5980-d531-11eb-8ed9-da185b589aea.png)

Then click "outbound rules"

![image](https://user-images.githubusercontent.com/999897/123327129-f7a79180-d531-11eb-901a-ffa0f9f2ded7.png)

then find python on this list which should be highlighted in red to show it's being blocked and double click it. This should open up a dialogue box to enable such connections.

However! Please be very careful when altering your firewall, I would recommend discussing this with your local administrator!  Please let us know how you get on with this.

Thanks,
Amber

**Comment by sumin5784** [comment]
Hi Amber,

I was trying to use Epi2melabs on my own desktop, so there won't be issues. 
I'll try to follow steps you suggested, and get back with the results :)


Bests,
Sumin

**Comment by amblina** [comment]
Brill, let us know how you get on!

**Comment by spanferkelfan** [comment]
Hi!
We installed Epi2meLabs on our workstation and it worked fine. A few days later we installed the guppy_basecaller, now we can't start the labslauncher anymore. Did we overwrite some settings? Is there a way to have back the labslauncher without re-installing everything?
Cheers,
spanferkelfan

**Comment by amblina** [comment]
Hi @spanferkelfan I'm sorry to hear you're having issues - would you mind opening a separate issue, that way I can talk you through the steps and help you individually! Please include your launcher log and any extra details e.g. what platform you are running on.

New ticket can be created here: https://github.com/epi2me-labs/labslauncher/issues/new
Instructions on how to find your Launcher log: https://labs.epi2me.io/locating-the-labs-launcher-log-file/

Thanks!

> Hi!
> We installed Epi2meLabs on our workstation and it worked fine. A few days later we installed the guppy_basecaller, now we can't start the labslauncher anymore. Did we overwrite some settings? Is there a way to have back the labslauncher without re-installing everything?
> Cheers,
> spanferkelfan

**Comment by spanferkelfan** [comment]
Thank you amblina! I created a new ticket.

**Comment by mmnascimento** [comment]
> Hi Amber,
> 
> I attached screen shots here.
> 
> ![1](https://user-images.githubusercontent.com/65312235/120035472-46f6b280-bfc4-11eb-8c50-b5ce65126e6a.png)
> 
> ![2](https://user-images.githubusercontent.com/65312235/120035519-5d047300-bfc4-11eb-9ba0-0812e0829010.png)
> 
> ![3](https://user-images.githubusercontent.com/65312235/120035527-5f66cd00-bfc4-11eb-9269-262a904a7214.png)
> 
> ![4](https://user-images.githubusercontent.com/65312235/120035529-6097fa00-bfc4-11eb-8e79-33887e84e385.png)

Hi! I have these exact same issues on Ubuntu, how can I fix this?

**Comment by cjw85** [comment]
@mmnascimento I have moved your question to a new issue.

I am going to close this issue as it has become more of a forum with several users with possibly unrelated issues. Please open new issues as appropriate.
