### ISSUE TITLE
EPI2MElabs starts and then immediately exits

### ISSUE THREAD

**Issue by callumparr** [epi2me-labs/labslauncher#18]
I got some opening of the lablauncher, but I also had to manually pull the latest epi2melabs docker images independently of labslauncher as it wouldn't do it' 

I then start with labslauncher and comes with some exit error. I tried to restart it has error.

`ssh -Y -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxx`

`systemctl --user status docker.service` confirm docker is running.

`docker image pull  latest version of the epi2melabs docker images`

```
(base) callum@dgt-gpu2:~$ labslauncher 
[16:39:06 - labslauncher] Starting application.
[16:39:07 - DckrClnt] Creating docker client with options:
           image name: ontresearch/epi2melabs-notebook
           server name: Epi2Me-Labs-Server-callum
           data bind: /epi2melabs/
           command: start-notebook.sh  --NotebookApp.port_retries=0 --no-browser --notebook-dir=/
           host only: True
           fixed tag: None
           proxies: None
[16:39:07 - DckrClnt] Connection to docker (re)established.
[16:39:09 - Launcher] Status changed: 'unknown'->'exited'
[16:39:10 - Launcher] Application started.
[16:39:16 - DckrClnt] Removing container.
[16:39:16 - DckrClnt] Container removed.
[16:39:16 - Launcher] Status changed: 'exited'->'inactive'
[16:39:23 - DckrClnt] Starting container.
[16:39:23 - DckrClnt] Running notebook command as user 31381.
[16:39:23 - DckrClnt] Container environment: ['JUPYTER_ENABLE_LAB=yes'].
[16:39:26 - DckrClnt] Container started: 5d7308d4cada0b31d8d26d8b2c40b4ff6b04130306aef94b2d415516ef462110 ontresearch/epi2melabs-notebook:v1.1.0
[16:39:26 - Launcher] Status changed: 'inactive'->'running'
[16:39:27 - Launcher] Sending ping data, state=start.
[16:39:29 - Launcher] Container started, writing config to mount.
[16:39:29 - Launcher] Container started and primed.
[16:39:29 - Launcher] Status changed: 'running'->'exited'
```

**Comment by amblina** [comment]
Hi @callumparr ,
I've been able to replicate this locally and am looking into this, I will update you when there is a workaround  or update to fix.
Thank you for letting us know about this,
Amber

**Comment by amblina** [comment]
Hi @callumparr,

This is usually due to:

a. the port already being in use e.g. if you're running something else pointed at 8000
b. permissions issues with sharing on the required directories
c. docker running issue e.g. lack of space

### Checking ports are available via terminal:

Try running:
`lsof -i -P -n | grep LISTEN | grep 8888`

If nothing is returned then you don't have anything using that port and you can move onto the following steps.

### Checking sharing permissions

Please check docker has read/write permissions in the directory you've selected to share with Labslauncher. 

### Docker debugging via terminal

First we need to identify the container that exited prematurely.  This can be done by running this command:

`docker container ls -a`

If you've just had the epi2melabs container fail it should be near the top and look like this:

![image](https://user-images.githubusercontent.com/999897/123280396-a4691b00-d500-11eb-8266-018fd8bcd9f6.png)

Next take the container ID on that line - in the image above mine was `11e6a78eca1b` and run the following:

`docker logs 11e6a78eca1b`

This will show us the logs of the container before it exited and might indicate what the issue might be.  Please copy and paste these here and we'll try and give you further advice.  We are currently looking into ways of making this type of debugging faster for the future!

Thanks,
Amber

**Comment by callumparr** [comment]
I presume I should check ports being used on remote side? Either way I check both and nothing came up when searching `8888`.

For containers that exited under `docker container ls -a`:

```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED      STATUS                  PORTS     NAMES
6d52e7a95ea9   ontresearch/epi2melabs-notebook:v1.1.0   "tini -g -- run_as_u…"   3 days ago   Exited (1) 3 days ago             Epi2Me-Labs-Server-callum
3ba7380d14c8   hello-world                              "/hello"                 6 days ago   Exited (0) 6 days ago             fervent_davinci
```

```
Providing permissions to host user for notebook group...
Adding UID 31381 to notebook group as nbhost
Executing command as: nbhost (31381)
/usr/local/bin/start-notebook.sh: running hooks in /usr/local/bin/start-notebook.d
/usr/local/bin/start-notebook.sh: running /usr/local/bin/start-notebook.d/startup.sh
mkdir: cannot create directory ‘/epi2melabs//notebooks/’: Permission denied
```

we are using rootless-docker on this node and its started as a service using:
`systemctl --user start docker.service`

In this case I guess I cannot run the epi2melabs on this if we do not have read/write permissions. 

also wonder it is putting `/epi2melabs//notebooks` directory instead of `/epi2melabs/notebooks`

**Comment by callumparr** [comment]
An update:

From the other issue, I managed to get lablauncher rendering properly on my local machine but because I had recently forced the image pull by manually pulling the images and since there has been an update to epi2melabs from 1.1 to 1.2 I cannot even start the launcher now let alone start and then it exits. This is the same error I originally had when I tried to pull the original images to start the launcher and then resorted to manually getting the images myself through the docker command.

error logged as:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher/qtext.py", line 107, in run
  File "labslauncher/dockerutil.py", line 330, in pull_image
  File "labslauncher/dockerutil.py", line 145, in pull_with_progress
  File "docker/api/image.py", line 410, in pull
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 226, in _post
  File "requests/sessions.py", line 572, in post
  File "requests/sessions.py", line 524, in request
  File "requests/sessions.py", line 637, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by amblina** [comment]
@callumparr  would you mind sending me the whole log file so I can help get to the bottom of this!

**Comment by callumparr** [comment]
If try starting the container from the labslauncher GUI (Xforwarding session for diplsay)

```
(base) callum@dgt-gpu2:~$ labslauncher 
[02:09:50 - labslauncher] Starting application.
[02:09:51 - DckrClnt] Creating docker client with options:
           image name: ontresearch/epi2melabs-notebook
           server name: Epi2Me-Labs-Server-callum
           data bind: /epi2melabs/
           command: start-notebook.sh  --NotebookApp.port_retries=0 --no-browser --notebook-dir=/
           host only: False
           fixed tag: None
           proxies: None
[02:09:51 - DckrClnt] Connection to docker (re)established.
[02:09:53 - Launcher] Status changed: 'unknown'->'inactive'
[02:09:53 - Launcher] Launcher update available: v1.1.0 -> v1.2.0.
[02:09:53 - Launcher]   ### Changed
[02:09:53 - Launcher]   - Container only reported as running when notebook webserver is up.
[02:09:53 - Launcher]   ### Added
[02:09:53 - Launcher]   - Automatic port selection.
[02:09:53 - Launcher]   
[02:09:53 - Launcher] Application started.
[02:10:39 - DckrClnt] Starting container.
[02:10:40 - DckrClnt] Running notebook command as user 31381.
[02:10:40 - DckrClnt] Container environment: ['JUPYTER_ENABLE_LAB=yes'].
[02:10:40 - DckrClnt] Container started: b0d584981456a128ecbae89a63d9b76f93ee4851ef737431e7e3795dcdfbcbdb ontresearch/epi2melabs-notebook:v1.1.0
[02:10:41 - Launcher] Status changed: 'inactive'->'running'
[02:10:41 - Launcher] Sending ping data, state=start.
[02:10:42 - Launcher] Container started, writing config to mount.
[02:10:42 - Launcher] Container started and primed.
[02:10:43 - Launcher] Status changed: 'running'->'exited'
```

Is there some issue with the ping. Theres also another update to download and if I try updating through the lablauncher get the following error:

```
02:18:24 - DckrClnt] Creating docker client with options:
           image name: ontresearch/epi2melabs-notebook
           server name: Epi2Me-Labs-Server-callum
           data bind: /epi2melabs/
           command: start-notebook.sh  --NotebookApp.port_retries=0 --no-browser --notebook-dir=/
           host only: False
           fixed tag: None
           proxies: None
[02:18:24 - DckrClnt] Connection to docker (re)established.
[02:18:26 - Launcher] Status changed: 'unknown'->'exited'
[02:18:26 - Launcher] Launcher update available: v1.1.0 -> v1.2.0.
[02:18:26 - Launcher]   ### Changed
[02:18:26 - Launcher]   - Container only reported as running when notebook webserver is up.
[02:18:26 - Launcher]   ### Added
[02:18:26 - Launcher]   - Automatic port selection.
[02:18:26 - Launcher]   
[02:18:26 - Launcher] Application started.
[02:18:43 - Launcher] Starting thread to pull image.
[02:18:44 - DckrClnt] Starting pull of image tag: v1.1.1.
[02:18:44 - Runnabl] Failed to execute runnable:
fn: <bound method DockerClient.pull_image of <labslauncher.dockerutil.DockerClient object at 0x7f560019bbe0>>
args: ()
kwargs: {'progress': <bound PYQT_SIGNAL progress of WorkerSignals object at 0x7f56000821f0>, 'stopped': <threading.Event object at 0x7f560006eca0>}
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 597, in urlopen
  File "urllib3/connectionpool.py", line 354, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 637, in urlopen
  File "urllib3/util/retry.py", line 368, in increment
  File "urllib3/packages/six.py", line 685, in reraise
  File "urllib3/connectionpool.py", line 597, in urlopen
  File "urllib3/connectionpool.py", line 354, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labslauncher/qtext.py", line 107, in run
  File "labslauncher/dockerutil.py", line 330, in pull_image
  File "labslauncher/dockerutil.py", line 145, in pull_with_progress
  File "docker/api/image.py", line 410, in pull
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 226, in _post
  File "requests/sessions.py", line 572, in post
  File "requests/sessions.py", line 524, in request
  File "requests/sessions.py", line 637, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by callumparr** [comment]
When I try to see if anything is using the hose ports with 
`lsof -i -P -n | grep LISTEN | grep 8888`

Returns nothing:

`lsof -i -P -n `

```
(base) callum@dgt-gpu2:~$ lsof -i -P -n 
COMMAND       PID   USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
EPI2ME-La 4130665 callum    4u  IPv4 113708428      0t0  TCP 127.0.0.1:50632->127.0.0.1:6011 (ESTABLISHED)
EPI2ME-La 4130665 callum    7u  IPv4 113707561      0t0  TCP 10.64.130.134:44738->13.230.158.120:443 (ESTABLISHED)
```

If I look under systemctl --user status docker.service I can see it does mention that 0.0.0.0:8888 is being used. 

```
● docker.service - Docker Application Container Engine (Rootless)
     Loaded: loaded (/etc/xdg/systemd/user/docker.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-03-02 14:08:29 JST; 1min 38s ago
       Docs: https://docs.docker.com
   Main PID: 4134388 (rootlesskit)
     CGroup: /user.slice/user-31381.slice/user@31381.service/docker.service
             ├─4134388 rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/local/rootless-docker/bin/dockerd-rootless.sh --experimental --data-root=/data/docker/callum
             ├─4134408 /proc/self/exe --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/local/rootless-docker/bin/dockerd-rootless.sh --experimental --data-root=/data/docker/callum
             ├─4134437 slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 4134408 tap0
             ├─4134446 dockerd --experimental --data-root=/data/docker/callum
             └─4134493 containerd --config /run/user/31381/docker/containerd/containerd.toml --log-level info

Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.597158130+09:00" level=info msg="Loading containers: start."
Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.809473487+09:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.897675986+09:00" level=info msg="Loading containers: done."
Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.914663941+09:00" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: running in a user namespace" storage-driver=overlay2
Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.915052108+09:00" level=info msg="Docker daemon" commit=8728dd2 graphdriver(s)=overlay2 version=20.10.6
Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.915147050+09:00" level=info msg="Daemon has completed initialization"
Mar 02 14:08:29 dgt-gpu2 bash[4134446]: time="2022-03-02T14:08:29.952123457+09:00" level=info msg="API listen on /run/user/31381/docker.sock"
Mar 02 14:09:42 dgt-gpu2 bash[4134446]: time="2022-03-02T14:09:42.689357421+09:00" level=warning msg="Failed to allocate and map port 8888-8888: Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:8888: bind: address already in use"
Mar 02 14:09:42 dgt-gpu2 bash[4134446]: time="2022-03-02T14:09:42.785944837+09:00" level=error msg="9977422833b8cc1d43b75fb231858fcba3fb960450b8fe14cff68dbc46f010d7 cleanup: failed to delete container from containerd: no such container"
Mar 02 14:09:42 dgt-gpu2 bash[4134446]: time="2022-03-02T14:09:42.786082104+09:00" level=error msg="Handler for POST /v1.35/containers/9977422833b8cc1d43b75fb231858fcba3fb960450b8fe14cff68dbc46f010d7/start returned error: driver failed programming external connectivity on endpoint Epi2Me-Labs-Server-callum (7eb092c8f593f47c71eae3ec125bc1d13ba7c6a3ed4b33fbe4b87b75f81babfc): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:8888: bind: address already in use"
```

If I change to 9000 or something then try restart launcher I then get back to issue of it not being able to create directory epi2melabs/notebooks

```
(base) callum@dgt-gpu2:~$ docker logs Epi2Me-Labs-Server-callum 
Providing permissions to host user for notebook group...
Adding UID 31381 to notebook group as nbhost
Executing command as: nbhost (31381)
/usr/local/bin/start-notebook.sh: running hooks in /usr/local/bin/start-notebook.d
/usr/local/bin/start-notebook.sh: running /usr/local/bin/start-notebook.d/startup.sh
mkdir: cannot create directory ‘/epi2melabs//notebooks/’: Permission denied

```
