### ISSUE TITLE
epi2me lab launcher v2.0.0

### ISSUE THREAD

**Issue by toptant** [epi2me-labs/labslauncher#24]
I installed the new update and version of the epi2me lab launcher as suggested on a windows and ubuntu machen using the given link below.
https://labs.epi2me.io/downloads
But none of them seem to work.
Failed to execute script 'labslauncher-script' due to unhandled exception: expected str, bytes, or os....
Traceback (most recent call last):
  File "labslauncher-script.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "labslauncher\app.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "epi2melabs\workflows\launcher.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "nf_core\schema.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "nf_core\list.py", line 22, in <module>
  File "nf_core\utils.py", line 311, in setup_requests_cachedir
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by toptant** [comment]
Hi,
I wanted to ask whether there is new news regarding the issues for epi2me lab launcher.

Best,
Tuna

**Comment by cjw85** [comment]
We are hoping to make a new release shortly in the next few hours.

**Comment by cjw85** [comment]
v2.0.1 has now been released.
