### ISSUE TITLE
Not able to install labslauncher on Ubuntu 18.04

### ISSUE THREAD

**Issue by Chandrak1907** [epi2me-labs/labslauncher#29]
I am following instructions mentioned [here](https://github.com/epi2me-labs/labslauncher) on Ubuntu 18.04 with python 3.7.11 and I get an error. Could you pls help?

```
(py369) ubuntu@instance-20220314-2104:~/labslauncher$ PYTHON=python3 make run
# "downgrade" to pyqt5 if ubuntu 16.04/18.04 or centos 7
if [[ "bionic" == "xenial" || "bionic" == "bionic" || -f /etc/centos-release ]]; then \
	echo "Switching to PyQt5"; \
	sed -r -i "s/#*pyqt5/pyqt5/" requirements.txt; \
	sed -r -i "s/#*pyqt6/#pyqt6/" requirements.txt; \
	else \
	echo "Switching to PyQt6"; \
	sed -r -i "s/#*pyqt5/#pyqt5/" requirements.txt; \
	sed -r -i "s/#*pyqt6/pyqt6/" requirements.txt; \
	fi
Switching to PyQt5
Project: ont-epi2melabs-launcher
Conflicts project: ont-epi2melabs-launcher-jupyter
Shell: 'Linux'
Python: python3
test -d venv || python3 -m venv venv
. ./venv/bin/activate && pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in ./venv/lib/python3.7/site-packages (22.0.4)
Requirement already satisfied: setuptools in ./venv/lib/python3.7/site-packages (44.1.1)
Collecting setuptools
  Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
Requirement already satisfied: wheel in ./venv/lib/python3.7/site-packages (0.37.1)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
      Successfully uninstalled setuptools-44.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
labslauncher 2.0.2 requires setuptools<45, but you have setuptools 60.9.3 which is incompatible.
Successfully installed setuptools-60.9.3
. ./venv/bin/activate && pip install $(grep "^pyqt.-sip" requirements.txt) 
Requirement already satisfied: pyqt5-sip==12.9.0 in ./venv/lib/python3.7/site-packages (12.9.0)
. ./venv/bin/activate && pip install -e . && labslauncher
Obtaining file:///home/ubuntu/labslauncher
  Preparing metadata (setup.py) ... done
Requirement already satisfied: anyascii==0.3.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (0.3.0)
Requirement already satisfied: cachetools==4.1.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (4.1.0)
Requirement already satisfied: docker==4.2.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (4.2.0)
Requirement already satisfied: epi2melabs>=0.0.24 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (0.0.28)
Requirement already satisfied: flask==2.0.2 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (2.0.2)
Requirement already satisfied: flask_restful==0.3.9 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (0.3.9)
Requirement already satisfied: Markdown==3.2.2 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (3.2.2)
Requirement already satisfied: password_strength==0.0.3.post2 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (0.0.3.post2)
Requirement already satisfied: portpicker==1.4.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (1.4.0)
Requirement already satisfied: psutil==5.8.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (5.8.0)
Requirement already satisfied: PyInstaller==4.7 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (4.7)
Requirement already satisfied: PyGithub==1.54 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (1.54.0)
Requirement already satisfied: pyqt5==5.15.6 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (5.15.6)
Requirement already satisfied: pyqt5-sip==12.9.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (12.9.0)
Requirement already satisfied: QtPy==2.0.1 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (2.0.1)
Requirement already satisfied: ratelimitingfilter==1.2 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (1.2)
Requirement already satisfied: semver==2.13.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (2.13.0)
Collecting setuptools<45
  Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
Requirement already satisfied: netifaces>=0.11.0 in ./venv/lib/python3.7/site-packages (from labslauncher==2.0.2) (0.11.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in ./venv/lib/python3.7/site-packages (from docker==4.2.0->labslauncher==2.0.2) (2.24.0)
Requirement already satisfied: websocket-client>=0.32.0 in ./venv/lib/python3.7/site-packages (from docker==4.2.0->labslauncher==2.0.2) (1.3.1)
Requirement already satisfied: six>=1.4.0 in ./venv/lib/python3.7/site-packages (from docker==4.2.0->labslauncher==2.0.2) (1.16.0)
Requirement already satisfied: itsdangerous>=2.0 in ./venv/lib/python3.7/site-packages (from flask==2.0.2->labslauncher==2.0.2) (2.1.1)
Requirement already satisfied: Werkzeug>=2.0 in ./venv/lib/python3.7/site-packages (from flask==2.0.2->labslauncher==2.0.2) (2.0.3)
Requirement already satisfied: click>=7.1.2 in ./venv/lib/python3.7/site-packages (from flask==2.0.2->labslauncher==2.0.2) (8.0.4)
Requirement already satisfied: Jinja2>=3.0 in ./venv/lib/python3.7/site-packages (from flask==2.0.2->labslauncher==2.0.2) (3.0.3)
Requirement already satisfied: aniso8601>=0.82 in ./venv/lib/python3.7/site-packages (from flask_restful==0.3.9->labslauncher==2.0.2) (9.0.1)
Requirement already satisfied: pytz in ./venv/lib/python3.7/site-packages (from flask_restful==0.3.9->labslauncher==2.0.2) (2021.3)
Requirement already satisfied: importlib-metadata in ./venv/lib/python3.7/site-packages (from Markdown==3.2.2->labslauncher==2.0.2) (4.11.3)
Requirement already satisfied: deprecated in ./venv/lib/python3.7/site-packages (from PyGithub==1.54->labslauncher==2.0.2) (1.2.13)
Requirement already satisfied: pyjwt<2.0 in ./venv/lib/python3.7/site-packages (from PyGithub==1.54->labslauncher==2.0.2) (1.7.1)
Requirement already satisfied: altgraph in ./venv/lib/python3.7/site-packages (from PyInstaller==4.7->labslauncher==2.0.2) (0.17.2)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in ./venv/lib/python3.7/site-packages (from PyInstaller==4.7->labslauncher==2.0.2) (2022.2)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in ./venv/lib/python3.7/site-packages (from pyqt5==5.15.6->labslauncher==2.0.2) (5.15.2)
Requirement already satisfied: packaging in ./venv/lib/python3.7/site-packages (from QtPy==2.0.1->labslauncher==2.0.2) (21.3)
Requirement already satisfied: jsonschema in ./venv/lib/python3.7/site-packages (from epi2melabs>=0.0.24->labslauncher==2.0.2) (4.4.0)
Requirement already satisfied: colorama in ./venv/lib/python3.7/site-packages (from epi2melabs>=0.0.24->labslauncher==2.0.2) (0.4.4)
Requirement already satisfied: sqlalchemy in ./venv/lib/python3.7/site-packages (from epi2melabs>=0.0.24->labslauncher==2.0.2) (1.4.32)
Requirement already satisfied: shortuuid in ./venv/lib/python3.7/site-packages (from epi2melabs>=0.0.24->labslauncher==2.0.2) (1.0.8)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.7/site-packages (from Jinja2>=3.0->flask==2.0.2->labslauncher==2.0.2) (2.1.0)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.2.0->labslauncher==2.0.2) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.2.0->labslauncher==2.0.2) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.2.0->labslauncher==2.0.2) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.2.0->labslauncher==2.0.2) (3.0.4)
Requirement already satisfied: wrapt<2,>=1.10 in ./venv/lib/python3.7/site-packages (from deprecated->PyGithub==1.54->labslauncher==2.0.2) (1.14.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./venv/lib/python3.7/site-packages (from importlib-metadata->Markdown==3.2.2->labslauncher==2.0.2) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.7/site-packages (from importlib-metadata->Markdown==3.2.2->labslauncher==2.0.2) (3.7.0)
Requirement already satisfied: importlib-resources>=1.4.0 in ./venv/lib/python3.7/site-packages (from jsonschema->epi2melabs>=0.0.24->labslauncher==2.0.2) (5.4.0)
Requirement already satisfied: attrs>=17.4.0 in ./venv/lib/python3.7/site-packages (from jsonschema->epi2melabs>=0.0.24->labslauncher==2.0.2) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./venv/lib/python3.7/site-packages (from jsonschema->epi2melabs>=0.0.24->labslauncher==2.0.2) (0.18.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./venv/lib/python3.7/site-packages (from packaging->QtPy==2.0.1->labslauncher==2.0.2) (3.0.7)
Requirement already satisfied: greenlet!=0.4.17 in ./venv/lib/python3.7/site-packages (from sqlalchemy->epi2melabs>=0.0.24->labslauncher==2.0.2) (1.1.2)
Installing collected packages: setuptools, labslauncher
  Attempting uninstall: setuptools
    Found existing installation: setuptools 60.9.3
    Uninstalling setuptools-60.9.3:
      Successfully uninstalled setuptools-60.9.3
  Attempting uninstall: labslauncher
    Found existing installation: labslauncher 2.0.2
    Uninstalling labslauncher-2.0.2:
      Successfully uninstalled labslauncher-2.0.2
  Running setup.py develop for labslauncher
Successfully installed labslauncher-2.0.2 setuptools-44.1.1
Traceback (most recent call last):
  File "/home/ubuntu/labslauncher/venv/bin/labslauncher", line 11, in <module>
    load_entry_point('labslauncher', 'console_scripts', 'labslauncher')()
  File "/home/ubuntu/labslauncher/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/labslauncher/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ubuntu/labslauncher/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ubuntu/labslauncher/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/labslauncher/labslauncher/app.py", line 40, in <module>
    from epi2melabs.workflows.launcher import WorkflowLauncher # noqa
  File "/home/ubuntu/labslauncher/venv/lib/python3.7/site-packages/epi2melabs/workflows/launcher.py", line 118
    if workflow := self.workflows.get(name):
                 ^
SyntaxError: invalid syntax
Makefile:80: recipe for target 'run' failed
make: *** [run] Error 1 
```

**Comment by cjw85** [comment]
Hi @Chandrak1907,

The application now requires Python3.8. This change seems to have slipped through the net. We will release a fix shortly for this.

Note, we provide a Debian package for Ubuntu 18.04 on the release page: https://github.com/epi2me-labs/labslauncher/releases/tag/v2.0.2.
