### ISSUE TITLE
make run failing at epi2melabs install (PyQt?)

### ISSUE THREAD

**Issue by genignored** [epi2me-labs/labslauncher#35]
Hi, 
I have tried fighting this one on my own, but am not able to get past it.

During the `PYTHON=python3 make run ` step while installing labslauncher, I'm getting the same error, regardless of what I do.

```
Requirement already satisfied: zipp>=3.1.0 in ./venv/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema->epi2melabs>=0.0.43->labslauncher==3.1.5) (3.11.0)
Installing collected packages: labslauncher
  Attempting uninstall: labslauncher
    Found existing installation: labslauncher 3.1.5
    Uninstalling labslauncher-3.1.5:
      Successfully uninstalled labslauncher-3.1.5
  Running setup.py develop for labslauncher
Successfully installed labslauncher-3.1.5
Traceback (most recent call last):
  File "/data/mscholz_software/conda_envs/epi2/labslauncher/labslauncher-3.1.5/venv/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: /lib64/libgssapi_krb5.so.2: symbol krb5_ser_context_init, version krb5_3_MIT not defined in file libkrb5.so.3 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/mscholz_software/conda_envs/epi2/labslauncher/labslauncher-3.1.5/venv/bin/labslauncher", line 33, in <module>
    sys.exit(load_entry_point('labslauncher', 'console_scripts', 'labslauncher')())
  File "/data/mscholz_software/conda_envs/epi2/labslauncher/labslauncher-3.1.5/venv/bin/labslauncher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/mscholz_software/conda_envs/epi2/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/data/mscholz_software/conda_envs/epi2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/mscholz_software/conda_envs/epi2/labslauncher/labslauncher-3.1.5/labslauncher/app.py", line 15, in <module>
    from labslauncher.gui import LabsLauncherGUI
  File "/data/mscholz_software/conda_envs/epi2/labslauncher/labslauncher-3.1.5/labslauncher/gui.py", line 16, in <module>
    from qtpy.QtWebEngineWidgets import QWebEngineView
  File "/data/mscholz_software/conda_envs/epi2/labslauncher/labslauncher-3.1.5/venv/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
make: *** [run] Error 1
```

I have tried:
1) activating the virtual environment, and manually installing PyQt, and PyQt5WebEngine
2) Installing both PyQt and PyQTWebEngine in my current environment
3) Running installation steps manually in a conda environment

If this has come up before I can't find it in open or closed issues, but I may not be looking in the right places.  Any help would be greatly appreciated.

Thank you,

**Comment by mattdmem** [comment]
Hello @genignored,

Please download the new version (EPI2ME Labs v4)  for your platform from here:https://labs.epi2me.io/downloads/

You do not need to build it yourself!

Thanks!

**Comment by cjw85** [comment]
Hi @genignored 

As noted in the [README](https://github.com/epi2me-labs/labslauncher#packages), packages are available from our [downloads](labs.epi2me.io/downloads) page.

Note also that this version of the program is now deprecated.

**Comment by genignored** [comment]
Hi,

@cjw85 I am not able to install from a package, as this is a shared system that is not running Ubuntu or Debian. 

When you say this is depreciated, what is the current tool to launch the EPI2MELabs instance?

**Comment by cjw85** [comment]
See the download link above

**Comment by genignored** [comment]
@cjw85 Unless I am missing something, there are no links to a source version of labslauncher v.4.  If I have missed it, please feel free to point it out. I am happy to try to install that way.  Otherwise I am stuck fighting PyQt, or finding another work around.

**Comment by cjw85** [comment]
We have no plans to release EPI2ME Labs v4 in a source-code form. We can create an RPM package and possibly a generic linux tarball if that is useful?
